---
  - name: enable nut
    service:
      name: "{{ item }}"
      enabled: "yes"
    with_items: "{{ sysutils_nut_service }}"

  - name: restart nut
    service:
      name: "{{ item }}"
      state: "restarted"
    with_items: "{{ sysutils_nut_service }}"
